FROM ubuntu:16.04
MAINTAINER rusetskialexander@gmail.com

COPY sources/venv /venv
COPY sources/Data_Optimization_Prototype/requirements.txt /requirements.txt


RUN adduser dop --shell /bin/bash --disabled-password --gecos "" && chown dop:dop /var/log -R
	#Install required packages

RUN apt-get update &&\
  apt-get install -y git\  
  supervisor\
  curl\
  python\
  python-virtualenv\
  build-essential\
  libssl-dev\
  libkrb5-dev\
  gcc\
  git\
  libmysqlclient-dev \
  mysql-client \
  python-dev libffi-dev \
  libkyotocabinet-dev \
  libxml2-dev \
  libxslt1-dev\
  nginx\
  vim
	

#Create virtual environment
ENV VENV /venv
RUN virtualenv --python=python2.7 $VENV
RUN $VENV/bin/pip install -r /requirements.txt

COPY react/nvm_install.sh /nvm_install.sh

COPY sources/Data_Optimization_Prototype /Data_Optimization_Prototype
WORKDIR /Data_Optimization_Prototype/react

        # Install nvm with node and npm
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.7.0 #0.12.16

##RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash \
RUN bash /nvm_install.sh \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default\
    && rm -rf ~/.node-gyp\
    && npm cache clear\
    && npm install\
    && npm install react-tipsy\
    && npm run build-amazon

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/v$NODE_VERSION/bin:$PATH

RUN echo '' > /var/log/app.log\
   && mkdir -p /Data_Optimization_Prototype/datatasks/db_files/\
   && mkdir /Data_Optimization_Prototype/media/export_files -p\
   && mkdir /var/log/ringlead\
   && chown dop:dop /var/log -R\
   && chown dop:dop /Data_Optimization_Prototype -R
   


