FROM ringleaddev/base
MAINTAINER rusetskialexander@gmail.com

WORKDIR /Data_Optimization_Prototype/

RUN mkdir -p  /Data_Optimization_Prototype/www/static\
  && mkdir -p /var/log/ringlead
  
COPY configs/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
COPY configs/supervisor/websockets.conf /etc/supervisor/conf.d/websockets.conf

RUN echo '' > /var/log/app.log\
   && chown dop:dop /var/log -R

COPY  websockets.sh /app/websockets.sh
