#django container
version: "2"
services:
  web:
    #image: 144049946307.dkr.ecr.us-west-2.amazonaws.com/dop-web:latest
    build: .
    command: /app/./all.sh
    volumes:
      - .:/app
      - /home/white/web:/cfgs
      - /volumes:/volumes            
    ports:
      - "80:80"
      - "443:443"    
    #restart: always
  
 
    
