FROM ubuntu:16.04

RUN apt-get update &&\
  apt-get install -y virtualenv\
  python-pip\
  gcc\
  git\
  libmysqlclient-dev \
  mysql-client \
  python-dev libffi-dev \ 
  libkyotocabinet-dev \
  libxml2-dev \
  libxslt1-dev\
  supervisor

COPY sources/Data_Optimization_Prototype /Data_Optimization_Prototype
COPY sources/venv /venv

WORKDIR /Data_Optimization_Prototype 

RUN virtualenv --python=python2.7 /venv

RUN . /venv/bin/activate; pip install -r requirements.txt

RUN mkdir -p  /Data_Optimization_Prototype/www/static\
  && mkdir -p /var/log/ringlead\
  && mkdir /app

RUN adduser dop --shell /bin/bash --disabled-password --gecos ""\ 
   && mkdir /Data_Optimization_Prototype/media/export_files -p\
   && chown dop:dop /var/log -R\
   && chown dop:dop /Data_Optimization_Prototype -R  

COPY celery.sh /app/celery.sh
RUN ls -alh /app/
